### ISSUE TITLE
`sxs.load` fails for `ExtraWaveforms.h5` data

### ISSUE THREAD

**Issue by keefemitman** [sxs-collaboration/sxs#111]
`sxs.load` fails for `ExtraWaveforms.h5` data, but `sxs.rpdmb.load` works

**Comment by moble** [comment]
It works for me.  You do have to pass a particular group, though.  E.g.,
```python
sxs.load("ExtraWaveforms.h5", group="/rMPsi4_Asymptotic_GeometricUnits_CoM_Mem/Extrapolated_N2.dir")
```

(Of course, for simulations that are already part of our catalog, you can just do things like `sxs.load("SXS:BBH:1234").psi4`, and not have to know anything about files or groups.)

**Comment by keefemitman** [comment]
Ah ok, thanks! I had just missed this syntax.
