### ISSUE TITLE
References to missing modules `sxs.data`, `sxs.data.api`

### ISSUE THREAD

**Issue by duetosymmetry** [sxs-collaboration/sxs#12]
Currently, `setup.py` refers to modules `sxs.data` and `sxs.data.api`:
https://github.com/sxs-collaboration/sxs/blob/1691b00253fcea365c30267a470916ee6a520754/setup.py#L56-L62

However, there are no such modules. A pip install will therefore error (and this is blocking me from adding auto-generated documentation on RTD).

**Comment by moble** [comment]
Sorry.  I forgot to add that directory, so it was working for all my build needs, and I just didn't notice.
