### ISSUE TITLE
Possible bug in metadata writing

### ISSUE THREAD

**Issue by SergeiOssokine** [sxs-collaboration/sxs#30]
There appears to be a bug in the method `to_json_file` in the `Metadata` class. In particular, this line:
https://github.com/sxs-collaboration/sxs/blob/main/sxs/metadata/metadata.py#L273
This line creates a directory ending in `.json` which breaks things. Removing seems to solve the issue.

**Comment by moble** [comment]
Thank.  It should be `path.parent` in that line.  I'll fix it shortly.
