### ISSUE TITLE
Add support for new metadata fields `keywords`, `warnings`, `superseded_by`

### ISSUE THREAD

**Issue by duetosymmetry** [sxs-collaboration/sxs#70]
* Use `keywords` field, which has short descriptions of systems
    * Can then add `deprecated` as a keyword
  * `warnings` should be a new field
  * `superseded_by` should be a new field
  * If sxs sees `deprecated`, refuse to load the file
    * If you really want to load this, use a new option
    * If `superseded_by` exists, recommend the newer waveform
  * If sxs sees `superseded_by`, suggest a different waveform
  * If `warnings` exist, issue the warnings

**Comment by markscheel** [comment]
Note that `superseded_by` may have more than one waveform listed.

**Comment by markscheel** [comment]
If `superseded_by` has more than one waveform, then sxs should list all of them and the user picks what is appropriate.
